"""add matchup_history and pitcher_game_log tables

Revision ID: 1a02dbc1df53
Revises: 6ebe1ce07e84
Create Date: 2026-07-10 20:31:35.725940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a02dbc1df53'
down_revision: Union[str, None] = '6ebe1ce07e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchup_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('at_bats', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('home_runs', sa.Integer(), nullable=False),
    sa.Column('strikeouts', sa.Integer(), nullable=False),
    sa.Column('batting_avg', sa.Float(), nullable=True),
    sa.Column('on_base_pct', sa.Float(), nullable=True),
    sa.Column('slugging_pct', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batter_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batter_id', 'pitcher_id', name='uq_matchup_history_batter_pitcher')
    )
    op.create_index(op.f('ix_matchup_history_batter_id'), 'matchup_history', ['batter_id'], unique=False)
    op.create_index(op.f('ix_matchup_history_pitcher_id'), 'matchup_history', ['pitcher_id'], unique=False)
    op.create_table('pitcher_game_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('opponent', sa.String(length=100), nullable=False),
    sa.Column('innings_pitched', sa.Float(), nullable=False),
    sa.Column('hits_allowed', sa.Integer(), nullable=False),
    sa.Column('earned_runs', sa.Integer(), nullable=False),
    sa.Column('walks', sa.Integer(), nullable=False),
    sa.Column('strikeouts', sa.Integer(), nullable=False),
    sa.Column('era', sa.Float(), nullable=True),
    sa.Column('whip', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pitcher_id', 'game_date', name='uq_pitcher_game_log_pitcher_date')
    )
    op.create_index(op.f('ix_pitcher_game_log_pitcher_id'), 'pitcher_game_log', ['pitcher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitcher_game_log_pitcher_id'), table_name='pitcher_game_log')
    op.drop_table('pitcher_game_log')
    op.drop_index(op.f('ix_matchup_history_pitcher_id'), table_name='matchup_history')
    op.drop_index(op.f('ix_matchup_history_batter_id'), table_name='matchup_history')
    op.drop_table('matchup_history')
    # ### end Alembic commands ###
