"""add game_odds table

Revision ID: 4887e9339c48
Revises: 32215d8c1f92
Create Date: 2026-05-24 14:25:59.940541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4887e9339c48'
down_revision: Union[str, None] = '32215d8c1f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_odds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('sportsbook', sa.String(length=40), nullable=False),
    sa.Column('home_moneyline', sa.Integer(), nullable=True),
    sa.Column('away_moneyline', sa.Integer(), nullable=True),
    sa.Column('spread_home', sa.Float(), nullable=True),
    sa.Column('spread_away', sa.Float(), nullable=True),
    sa.Column('over_under', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'sportsbook', 'fetched_at', name='uq_game_odds_game_book_fetched')
    )
    op.create_index(op.f('ix_game_odds_fetched_at'), 'game_odds', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_game_odds_game_id'), 'game_odds', ['game_id'], unique=False)
    op.create_index('ix_game_odds_game_sportsbook', 'game_odds', ['game_id', 'sportsbook'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_odds_game_sportsbook', table_name='game_odds')
    op.drop_index(op.f('ix_game_odds_game_id'), table_name='game_odds')
    op.drop_index(op.f('ix_game_odds_fetched_at'), table_name='game_odds')
    op.drop_table('game_odds')
    # ### end Alembic commands ###
