"""add pick_history table

Revision ID: 6ebe1ce07e84
Revises: b5f29d65d9ab
Create Date: 2026-05-27 02:19:06.424887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ebe1ce07e84'
down_revision: Union[str, None] = 'b5f29d65d9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pick_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('predicted_probability', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('actual_result', sa.String(length=10), nullable=False),
    sa.Column('factors_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='uq_pick_history_player_game')
    )
    op.create_index(op.f('ix_pick_history_game_id'), 'pick_history', ['game_id'], unique=False)
    op.create_index(op.f('ix_pick_history_player_id'), 'pick_history', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pick_history_player_id'), table_name='pick_history')
    op.drop_index(op.f('ix_pick_history_game_id'), table_name='pick_history')
    op.drop_table('pick_history')
    # ### end Alembic commands ###
