"""per-game pitcher stats and game probable pitchers

Revision ID: b5f29d65d9ab
Revises: ca57a832790e
Create Date: 2026-05-24 15:55:34.984364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5f29d65d9ab'
down_revision: Union[str, None] = 'ca57a832790e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('home_probable_pitcher_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_probable_pitcher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'players', ['home_probable_pitcher_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'games', 'players', ['away_probable_pitcher_id'], ['id'], ondelete='SET NULL')
    op.add_column('pitcher_stats', sa.Column('game_id', sa.Integer(), nullable=True))
    op.add_column('pitcher_stats', sa.Column('is_season_aggregate', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('pitcher_stats', sa.Column('earned_runs', sa.Integer(), nullable=False))
    op.drop_constraint('uq_pitcher_stats_player_season', 'pitcher_stats', type_='unique')
    op.create_index('uq_pitcher_stats_game', 'pitcher_stats', ['player_id', 'game_id'], unique=True, postgresql_where=sa.text('NOT is_season_aggregate'))
    op.create_index('uq_pitcher_stats_season', 'pitcher_stats', ['player_id', 'season'], unique=True, postgresql_where=sa.text('is_season_aggregate'))
    op.create_foreign_key(None, 'pitcher_stats', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitcher_stats', type_='foreignkey')
    op.drop_index('uq_pitcher_stats_season', table_name='pitcher_stats', postgresql_where=sa.text('is_season_aggregate'))
    op.drop_index('uq_pitcher_stats_game', table_name='pitcher_stats', postgresql_where=sa.text('NOT is_season_aggregate'))
    op.create_unique_constraint('uq_pitcher_stats_player_season', 'pitcher_stats', ['player_id', 'season'], postgresql_nulls_not_distinct=False)
    op.drop_column('pitcher_stats', 'earned_runs')
    op.drop_column('pitcher_stats', 'is_season_aggregate')
    op.drop_column('pitcher_stats', 'game_id')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'away_probable_pitcher_id')
    op.drop_column('games', 'home_probable_pitcher_id')
    # ### end Alembic commands ###
