"""add pitcher_stats and player handedness

Revision ID: ca57a832790e
Revises: 4887e9339c48
Create Date: 2026-05-24 14:55:48.238521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca57a832790e'
down_revision: Union[str, None] = '4887e9339c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitcher_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('innings_pitched', sa.Float(), nullable=False),
    sa.Column('hits_allowed', sa.Integer(), nullable=False),
    sa.Column('walks_allowed', sa.Integer(), nullable=False),
    sa.Column('strikeouts', sa.Integer(), nullable=False),
    sa.Column('era', sa.Float(), nullable=True),
    sa.Column('whip', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='uq_pitcher_stats_player_season')
    )
    op.create_index(op.f('ix_pitcher_stats_player_id'), 'pitcher_stats', ['player_id'], unique=False)
    op.add_column('players', sa.Column('bats', sa.String(length=1), nullable=True))
    op.add_column('players', sa.Column('throws', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'throws')
    op.drop_column('players', 'bats')
    op.drop_index(op.f('ix_pitcher_stats_player_id'), table_name='pitcher_stats')
    op.drop_table('pitcher_stats')
    # ### end Alembic commands ###
